name: "AzureCLI"
version: "1.0.4"
slug: haazcli
description: "Run Azure CLI commands"
startup: services
boot: auto
init: false
ingress: false
arch:
  - amd64
host_network: true
options:
  tenant_id: null
  client_id: null
  client_secret: null
schema:
  tenant_id: str
  client_id: str
  client_secret: password
ports:
  5902/tcp: 5902