name: MariaDB Backup
version: "2.2"
slug: mariadb-backup
description: Backup MariaDB databases using mariadb-dump
startup: once
boot: manual
arch:
  - amd64
  - aarch64
init: false
host_network: true
privileged: []
map:
  - share:rw
options:
  DB_HOST: core-mariadb
  DB_USER: homeassistant
  DB_PASS: yourpassword
  DB_BACKUPDIR: /share
  DB_RETENTION_DAYS: 60
schema:
  DB_HOST: str
  DB_USER: str
  DB_PASS: password
  DB_BACKUPDIR: str
  DB_RETENTION_DAYS: int
