name: MariaDB Backup
version: "2.3"
slug: mariadb-backup
description: Backup MariaDB databases using mariadb-dump
startup: once
boot: manual
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
host_network: true
privileged: []
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
options:
  DB_HOST: core-mariadb
  DB_USER: homeassistant
  DB_PASS: yourpassword
  DB_BACKUPDIR: /share
  DB_RETENTION_DAYS: 60
schema:
  DB_HOST: str
  DB_USER: str
  DB_PASS: password
  DB_BACKUPDIR: str
  DB_RETENTION_DAYS: int
