name: MariaDB Backup
version: "2.0"
slug: mariadb-backup
description: Backup MariaDB databases using mysqldump
startup: once
boot: manual
arch:
  - amd64
  - aarch64
init: false
host_network: true
privileged: []
map:
  - share:rw
options:
  DB_HOST: core-mariadb
  DB_USER: homeassistant
  DB_PASS: yourpassword
  DB_BACKUPDIR: /backup/location
schema:
  DB_HOST: str
  DB_USER: str
  DB_PASS: password
  BACKUPDIR: str
